### ISSUE TITLE
is the executable missing in the exercise folder?

### ISSUE THREAD

**Issue by jchain** [BigPino67/Tesseract-MICR-OCR#1]
It looks like to me that you use the tesseract c# binding. But I can not find the exe file. Did you forget to upload the .exe file or purposefully do so?

**Comment by BigPino67** [comment]
Hi jchain

You make me realize that i've forgot to write prerequisites. You need to install Tesseract for windows, link : https://code.google.com/p/tesseract-ocr/downloads/detail?name=tesseract-ocr-setup-3.02.02.exe&can=2&q= . Tell me if this works.

Thank you

**Comment by jchain** [comment]
I thought you also shared your gui tool for MICR reading. That was why I asked for the missing exe. If you don't want to share it, please feel free to ignore my request.

**Comment by BigPino67** [comment]
My GUI tool is the exercice to do. I can share you a version with EMGU (for matching template) once I come back at home tonight. Is it OK ?

**Comment by jchain** [comment]
It is great! I think it will be a good idea to upload it to github.

**Comment by BigPino67** [comment]
Hi jchain, i've commit the solution to the branch. You are now good to go! Tell me what you think!
