### ISSUE TITLE
Inaccurate result

### ISSUE THREAD

**Issue by sushantNoida** [BigPino67/Tesseract-MICR-OCR#2]
Tesseract-MICR-OCR is a nice framework. I got the inaccurate result on trying to get MICR (using micr.traineddata) from Cheque. It just gives routing number as MICR, no details about cheque number etc. Got the issue on following android devices ( Samsung Galaxy S4, Samsung Galaxy S5, MotoG4, Nexus 5).

**Comment by BigPino67** [comment]
The MICR trained data is really basic for this example. I've train this file only with the original font, it might gives you the result you have. There is 2 solutions :
1- Train your own language data for MICR
2- Find a MICR traineddata already well trained. You can get one from Tesseract-OCR Google groups by following this link : https://groups.google.com/forum/#!searchin/tesseract-ocr/micr/tesseract-ocr/obWI4cz8rXg/_Yl8RuCeJAkJ

Good luck, keep me up to date

**Comment by kirantpatil** [comment]
Hi @BigPino67,

I used your and as well google group mcr.traineddata to get MICR of HDFC check which is attached below.

But some of the 0 digits in MICR are converted to 8 as below.

@524000@ 695248882[ 045504@ 31

Please let me know, how to resolve this issue ?

![hdfcbank-before-cts-2010](https://user-images.githubusercontent.com/1178055/29158337-43071cc4-7dc8-11e7-80fc-21e660018a40.jpg)

Thanks.

**Comment by kirantpatil** [comment]
For SBI, 

@500201@ 695002017[ 01085- -

![sbi-before-cts-2010](https://user-images.githubusercontent.com/1178055/29158927-75c79ad8-7dca-11e7-95ee-dfc042a92e6f.jpg)

**Comment by kirantpatil** [comment]
I see the different results for different bank checks. I used the JPG files, is that an issue ? I converted JPG to Tiff and still the result is same.

Please let me know how should I move forward.

I used your mcr.traineddata from my ubuntu system.

#### $ tesseract --version
tesseract 3.03
 leptonica-1.70
  libgif 4.1.6(?) : libjpeg 8d : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : webp 0.4.0


I hope that should not be an issue.

**Comment by BigPino67** [comment]
Hello @kirantpatil 
Thank you for trying my tesseract project. First of all, TIFF is way better than jpeg but your image must be a tiff format at start, a jpeg converted to tiff is not the best way.

To get better accuracy, you should train your own micr langage.

Hope I've help you enough for your project!

**Comment by kirantpatil** [comment]
Dear @sushantNoida,

Were you able to resolve your issue ?

If resolved, please let me know your approach for the same.

Do you use any stock android app then please share the app link to download and test ?

Thanks.

**Comment by faaiz09** [comment]
I am facing the same issue. Can someone provide me with the new updated mcr.traineddata file !
The google lens scans the cheque number better and I want to get the same result using tesseract OCR
