### ISSUE TITLE
[FAQ] Extract MICR Result in to app

### ISSUE THREAD

**Issue by kirantpatil** [BigPino67/Tesseract-MICR-OCR#4]
Hi @BigPino67,

How are you are able to extract MICR code from below image in your app text field ?

I know this is a trivial question, since I am new to this field, would like to know the logic to extract it.

https://raw.githubusercontent.com/BigPino67/Tesseract-MICR-OCR/master/readmeImages/exercice.png

Thanks.

**Comment by BigPino67** [comment]
Hi @kirantpatil 

You can find the solution to the training I've propose here : 

https://github.com/BigPino67/Tesseract-MICR-OCR/tree/master/solution/OCRA_TEST

I've have  a bit use OOP for this, there is 3 classes you might be interested to look at :

1. Template.vb
2. TemplateMicrAnchor.vb
3. TemplateMicrXY.vb

I think you should be able to make it work!

**Comment by kirantpatil** [comment]
Hi @BigPino67,

Thanks, I am looking in to it.

**Comment by enu1302** [comment]
Plz share how to read micr code using training data...i have also use mcr.traineddata...but not able to read...
