### ISSUE TITLE
How training is done ?

### ISSUE THREAD

**Issue by GhadaJouini** [BigPino67/Tesseract-MICR-OCR#8]
Hello, thanks for this project :) it's very helpful 
This is not an issue but can anyone explain to me how the training is done exactly?

Any help is appreciated thanks!

**Comment by BigPino67** [comment]
Hello @GhadaJouini, I'm glad to read that :D

First, I've not test anything with Tesseract 4.0 so I dont know if it's the same as the version 3.0. But here is how I've achieved the training.

In my case, I work in a place where I have multiple stubs and cheques. So the goal is to build an image file with multiple OCR line. When it's done, I've loaded the image in jTessBoxEditor. And then, for every Character the application has detected, verify the result and correct it if there is a wrong recognition. Do this for every Character. And then, you'll have your trainedData for OCR. If you want MICR trained_data as well, repeat all these processes. The more you train your data, more accurate results you'll get from the engine.

I believe jTessBoxEditor is not supported for Tesseract 4.0. There is certainly a way to achieve the same processes. You'll need some research if you choose the most recent version of Tesseract.

Good luck!
